name: Windows

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/checkout@v3
      - name: Set up JDK 8
        # 安装jdk8环境(且要含有javafx)
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          java-package: 'jdk+fx'

      - name: Build with Maven
        # 执行打包的mvn命令
        run: mvn jfx:native `-Dmaven.test.skip=true

      # 移动打包文件
      - run: mkdir staging && cp -R target/jfx/native/* staging
      - run: tree target/jfx/native/
      - run: tree staging/
      - run: ls staging/


      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: D:\a\spider_client\spider_client\target\jfx\native\trex-stateless-gui

#
#

#      - name: Set Release version env variable
#        run: |
#          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
#      - name: "Build & test"
#        run: |
#          echo "done!"
          

      # 创建一个release,并将打包后的文件上传到附件
      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        uses: marvinpinto/action-automatic-releases@latest
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.0.1"
          prerelease: false
          title: "Release 1.0.1"
          # Assets to upload to the release
          files: |
            staging/**
